### ISSUE TITLE
Can you share the datasets used in the paper?

### ISSUE THREAD

**Issue by zdaiot** [ZJZAC/Deep-Model-Watermarking#1]

**Comment by ZJZAC** [comment]
We utilize the open dataset such as COCO and VOC, the further image processing method is also mentioned in our paper (refer to the corresponding citation, e.g., "Density-aware single image de-raining using a multi-stream dense networ" for derain task). BTW, the dataset for debone is not permitted for public release because of some commercial reason, nevertheless, we also provide the related algorithm for debone task in our paper. In addition, it is accessible to other open dataset based on pair data for image processing task to justify our method, refer to "https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix".
